#!/bin/bash
#iptables -A INPUT -i eth1 -p tcp --dport 80 -j ACCEPT
#iptables -A INPUT -i eth1 -p tcp --dport 8090 -j ACCEPT

#iptables -A PREROUTING -t nat -i eth1 -p tcp --dport 80 -j REDIRECT --to-port 8090

iptables -A INPUT -i eth0 -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -i eth0 -p tcp --dport 8090 -j ACCEPT

iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8090



iptables -A INPUT -i ham0 -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -i ham0 -p tcp --dport 8090 -j ACCEPT

iptables -A PREROUTING -t nat -i ham0 -p tcp --dport 80 -j REDIRECT --to-port 8090


